default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST") { ENV["HOME"] + "/postgres_data" } %>
  port: 5434
  username: gs

development:
  <<: *default
  database: rails_project_development

test:
  <<: *default
  database: rails_project_test

production:
  primary:
    <<: *default
    database: rails_project_production
